kind: Cluster
name: everstake-omni
talos:
  version: v1.9.4
kubernetes:
  version: 1.32.2
features:
  enableWorkloadProxy: true
patches:
  - name: cni
    file: patches/cni.yaml
  - name: mayastor-admission
    file: patches/mayastor-admission.yaml
  - name: metrics-server
    file: patches/metrics-server.yaml
---
kind: ControlPlane
machineClass:
  name: everstake-controlplane
  size: 1
patches:
  - name: cilium
    file: patches/cilium.yaml
  - name: argocd
    file: patches/argocd.yaml
  - name: monitoring
    file: patches/monitoring.yaml
  - name: control-plane
    file: patches/controlplane.yaml
  - name: mayastor
    file: patches/mayastor.yaml
---
kind: Workers
name: workers
machineClass:
  name: everstake-workers
  size: unlimited
patches:
  - name: mayastor
    file: patches/mayastor.yaml
